name: "Medl FrontEnd Deploy"
description: "Deploys MedlFrontEnds to S3"
inputs:
  aws-region:
    description: "AWS Region"
    required: false
    default: us-east-1
  build-folder-name:
    required: true
    description: "Name of the Build Folder"
outputs:
  nothing:
    description: "Just a simple string"
    value: "Pushed"
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ github.ref_name == 'staging' && format('arn:aws:iam::973525173731:role/tf-frontend-{0}-role', github.event.repository.name) || github.ref_name == 'sandbox' && format('arn:aws:iam::823876827192:role/tf-frontend-{0}-role', github.event.repository.name) || format('arn:aws:iam::117979148410:role/tf-frontend-{0}-role', github.event.repository.name) }}
        role-session-name: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
    - name: Sync to S3
      run: aws s3 sync ${{ inputs.build-folder-name }} ${{ github.ref_name == 'staging' && format('s3://{0}.staging.medl.me', github.event.repository.name) || github.ref_name == 'sandbox' && format('s3://{0}.sandbox.medl.me', github.event.repository.name) || format('s3://{0}.production.medl.me', github.event.repository.name) }} --acl public-read --delete
      shell: bash
